"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ShieldCheck, Phone, X, Shield, FileText, Scale } from "lucide-react";
import EmergencyModal from "./EmergencyModal";

export default function Footer() {
  const [isEmergencyModalOpen, setIsEmergencyModalOpen] = useState(false);
  const [legalModalContent, setLegalModalContent] = useState<{
    title: string;
    icon: any;
    content: string[];
  } | null>(null);

  const openLegalModal = (type: "privacy" | "terms" | "disclaimer") => {
    if (type === "privacy") {
      setLegalModalContent({
        title: "Privacy & Data Protection Policy",
        icon: Shield,
        content: [
          "Alaafia is committed to safeguarding your personal health information.",
          "Voice recordings and symptom transcriptions are end-to-end encrypted during transit and processed strictly for triage routing.",
          "We do not sell, rent, or monetize personal health inquiries to third-party advertisers.",
          "You retain full control over your consultation history and can export or delete your profile data at any time in Settings.",
        ],
      });
    } else if (type === "terms") {
      setLegalModalContent({
        title: "Terms of Service",
        icon: Scale,
        content: [
          "Alaafia is an AI-powered healthcare navigation and triage assistant, not a licensed physician or medical diagnosis provider.",
          "Information generated by Alaafia is intended for navigational and triage purposes to help users identify appropriate healthcare resources.",
          "Always consult qualified clinical practitioners for prescription decisions, emergency intervention, or definitive medical diagnosis.",
        ],
      });
    } else {
      setLegalModalContent({
        title: "Medical & Emergency Disclaimer",
        icon: FileText,
        content: [
          "CRITICAL NOTICE: Alaafia does not provide emergency medical treatment.",
          "If you or someone around you is experiencing life-threatening signs (such as sudden severe chest pressure, unconsciousness, severe difficulty breathing, or stroke symptoms), call national emergency services (112 / 767) immediately or proceed to the nearest emergency room.",
        ],
      });
    }
  };

  return (
    <>
      {/* Light Mint/Cyan Figma Footer Background */}
      <footer className="bg-[#d5ede9] text-[#1f4e4e] border-t border-teal-200/80 px-4 sm:px-8 pt-16 pb-12">
        <div className="max-w-6xl mx-auto space-y-12">
          {/* Top Row: Brand & Quick Emergency Banner */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Brand Information */}
            <div className="lg:col-span-5 space-y-4">
              <Link href="/" className="flex items-center gap-2.5 cursor-pointer group">
                <div className="flex items-center gap-0.5 h-6">
                  <span className="w-1 h-3.5 bg-[#006666] rounded-full group-hover:h-4 transition-all" />
                  <span className="w-1 h-5.5 bg-[#006666] rounded-full group-hover:h-6 transition-all" />
                  <span className="w-1 h-4 bg-[#006666] rounded-full group-hover:h-5 transition-all" />
                  <span className="w-1 h-5 bg-[#006666] rounded-full group-hover:h-5.5 transition-all" />
                </div>
                <span className="text-2xl font-extrabold text-[#005c6e] tracking-tight">
                  Alaafia
                </span>
              </Link>

              <p className="text-[#2c5e5e] text-sm leading-relaxed max-w-sm font-medium">
                Alaafia AI turns complex, uncertain symptoms into clear next steps and safe healthcare routing. Built for fast, reliable, voice-first triage.
              </p>

              <div className="inline-flex items-center gap-2 text-xs text-[#004d4d] bg-white/80 border border-teal-300/80 px-3 py-1.5 rounded-full font-bold shadow-2xs">
                <ShieldCheck className="w-4 h-4 text-[#006666]" />
                <span>Verified Clinical Safety Rules Active</span>
              </div>
            </div>

            {/* Quick Navigation Links */}
            <div className="lg:col-span-7 grid grid-cols-2 sm:grid-cols-3 gap-8 text-xs sm:text-sm">
              <div className="space-y-3">
                <h4 className="font-extrabold text-[#004d4d] uppercase text-xs tracking-wider">
                  Platform
                </h4>
                <ul className="space-y-2 text-[#2c5e5e] font-medium">
                  <li>
                    <Link href="/" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link href="/how-it-works" className="hover:text-[#005c6e] hover:underline transition-colors">
                      How It Works
                    </Link>
                  </li>
                  <li>
                    <Link href="/services" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Services
                    </Link>
                  </li>
                  <li>
                    <Link href="/safety" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Safety & Protocols
                    </Link>
                  </li>
                  <li>
                    <Link href="/consultation" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Start Consultation
                    </Link>
                  </li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-extrabold text-[#004d4d] uppercase text-xs tracking-wider">
                  Patient Hub
                </h4>
                <ul className="space-y-2 text-[#2c5e5e] font-medium">
                  <li>
                    <Link href="/about" className="hover:text-[#005c6e] hover:underline transition-colors">
                      About Alaafia
                    </Link>
                  </li>
                  <li>
                    <Link href="/dashboard" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Patient Portal
                    </Link>
                  </li>
                  <li>
                    <Link href="/history" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Consultation History
                    </Link>
                  </li>
                  <li>
                    <Link href="/care-support" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Care Support Fund
                    </Link>
                  </li>
                  <li>
                    <Link href="/emergency" className="hover:text-[#005c6e] hover:underline transition-colors">
                      Emergency Numbers
                    </Link>
                  </li>
                </ul>
              </div>

              <div className="space-y-3 col-span-2 sm:col-span-1">
                <h4 className="font-extrabold text-[#004d4d] uppercase text-xs tracking-wider">
                  Emergency Care
                </h4>
                <p className="text-xs text-[#2c5e5e] font-medium">
                  Experiencing life-threatening symptoms? Contact national emergency dispatch:
                </p>
                <Link
                  href="/emergency"
                  className="w-full inline-flex items-center justify-center gap-2 bg-[#b91c1c] hover:bg-[#991b1b] text-white text-xs font-extrabold py-2.5 px-3 rounded-xl transition-all shadow-md active:scale-95 cursor-pointer"
                >
                  <Phone className="w-3.5 h-3.5" />
                  <span>Call Emergency (112)</span>
                </Link>
              </div>
            </div>
          </div>

          {/* Bottom Row: Disclaimer & Copyright */}
          <div className="pt-8 border-t border-teal-200/80 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-[#386b6b] font-medium">
            <p>
              © 2026 Alaafia AI. All rights reserved. Medical triage assistant.
            </p>
            <div className="flex items-center gap-6">
              <button
                type="button"
                onClick={() => openLegalModal("privacy")}
                className="hover:text-[#004d4d] transition-colors cursor-pointer hover:underline"
              >
                Privacy Policy
              </button>
              <button
                type="button"
                onClick={() => openLegalModal("terms")}
                className="hover:text-[#004d4d] transition-colors cursor-pointer hover:underline"
              >
                Terms of Service
              </button>
              <button
                type="button"
                onClick={() => openLegalModal("disclaimer")}
                className="hover:text-[#004d4d] transition-colors cursor-pointer hover:underline"
              >
                Medical Disclaimer
              </button>
            </div>
          </div>
        </div>
      </footer>

      {/* Emergency Modal Popup */}
      <EmergencyModal
        isOpen={isEmergencyModalOpen}
        onClose={() => setIsEmergencyModalOpen(false)}
      />

      {/* Legal Dialog Modal */}
      {legalModalContent && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-fade-in">
          <div className="bg-white rounded-3xl p-6 sm:p-8 max-w-lg w-full shadow-2xl border border-slate-200 space-y-5 animate-scale-in">
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-teal-50 text-[#006666] flex items-center justify-center">
                  <legalModalContent.icon className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-slate-900">
                  {legalModalContent.title}
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setLegalModalContent(null)}
                className="text-slate-400 hover:text-slate-700 p-1.5 rounded-full hover:bg-slate-100 transition-colors"
                aria-label="Close legal modal"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-sm text-slate-600 leading-relaxed">
              {legalModalContent.content.map((paragraph, idx) => (
                <p key={idx} className="bg-slate-50 p-3.5 rounded-xl border border-slate-100">
                  {paragraph}
                </p>
              ))}
            </div>

            <div className="pt-2 flex justify-end">
              <button
                type="button"
                onClick={() => setLegalModalContent(null)}
                className="px-5 py-2.5 bg-[#006666] hover:bg-[#005c6e] text-white text-xs font-bold rounded-xl transition-all shadow-xs"
              >
                Understood & Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

