/**
 * Facility Seed Data
 * Simulated facilities for MVP testing
 * Lagos, Nigeria coordinates as base
 */

const facilitySeeds = [
  {
    name: "Lagos General Hospital",
    facilityType: "hospital",
    latitude: 6.5244,
    longitude: 3.3792,
    address: "Bariga, Lagos State, Nigeria",
    phone: "+234 1 263 0589",
    email: "info@lgh.ng",
    capabilities: [
      "emergency",
      "surgery",
      "cardiology",
      "neurology",
      "intensive_care",
      "obstetrics",
    ],
    emergencyCapable: true,
    dataSource: "simulated",
    verificationStatus: "verified",
  },
  {
    name: "Reddington Hospital",
    facilityType: "hospital",
    latitude: 6.4969,
    longitude: 3.5156,
    address: "Victoria Island, Lagos State, Nigeria",
    phone: "+234 1 461 7800",
    email: "info@reddington.ng",
    capabilities: [
      "emergency",
      "surgery",
      "cardiology",
      "intensive_care",
      "obstetrics",
      "pediatrics",
    ],
    emergencyCapable: true,
    dataSource: "simulated",
    verificationStatus: "verified",
  },
  {
    name: "Ikeja Medical Centre",
    facilityType: "urgent_care",
    latitude: 6.5822,
    longitude: 3.3398,
    address: "Ikeja, Lagos State, Nigeria",
    phone: "+234 1 493 2000",
    email: "info@ikejamedical.ng",
    capabilities: ["emergency", "surgery", "internal_medicine", "pediatrics"],
    emergencyCapable: true,
    dataSource: "simulated",
    verificationStatus: "verified",
  },
  {
    name: "Surulere Medical Clinic",
    facilityType: "clinic",
    latitude: 6.4964,
    longitude: 3.3684,
    address: "Surulere, Lagos State, Nigeria",
    phone: "+234 1 770 2000",
    email: "info@suruleremedical.ng",
    capabilities: ["internal_medicine", "pediatrics", "family_medicine"],
    emergencyCapable: false,
    dataSource: "simulated",
    verificationStatus: "unverified",
  },
  {
    name: "Island Emergency Centre",
    facilityType: "urgent_care",
    latitude: 6.4283,
    longitude: 3.4385,
    address: "Lekki, Lagos State, Nigeria",
    phone: "+234 1 290 3500",
    email: "info@islandemergncy.ng",
    capabilities: ["emergency", "cardiology", "surgery", "intensive_care"],
    emergencyCapable: true,
    dataSource: "simulated",
    verificationStatus: "verified",
  },
  {
    name: "Ikoyi Wellness Clinic",
    facilityType: "clinic",
    latitude: 6.4632,
    longitude: 3.4359,
    address: "Ikoyi, Lagos State, Nigeria",
    phone: "+234 1 465 3000",
    email: "info@ikoyiwellness.ng",
    capabilities: ["family_medicine", "pediatrics", "general_practice"],
    emergencyCapable: false,
    dataSource: "simulated",
    verificationStatus: "unverified",
  },
  {
    name: "Yaba Diagnostic Centre",
    facilityType: "clinic",
    latitude: 6.5089,
    longitude: 3.3654,
    address: "Yaba, Lagos State, Nigeria",
    phone: "+234 1 636 9000",
    email: "info@yabadiagnostic.ng",
    capabilities: ["diagnostics", "radiology", "laboratory"],
    emergencyCapable: false,
    dataSource: "simulated",
    verificationStatus: "unverified",
  },
  {
    name: "Ajah Emergency Hospital",
    facilityType: "hospital",
    latitude: 6.3958,
    longitude: 3.5215,
    address: "Ajah, Lagos State, Nigeria",
    phone: "+234 1 290 5000",
    email: "info@ajahemergency.ng",
    capabilities: [
      "emergency",
      "surgery",
      "cardiology",
      "intensive_care",
      "obstetrics",
    ],
    emergencyCapable: true,
    dataSource: "simulated",
    verificationStatus: "verified",
  },
];

module.exports = facilitySeeds;
